#!/usr/bin/env python
# wscript_build
#
# Copyright (c) 2010 Eduardo Niehues
# Distributed under the New BSD License; see LICENSE for details.

plugins = [
	{'source': 'testplugin.vala', 'target': 'xsirctest'},
	{'source': 'highlights.vala', 'target': 'xsirchighlights', 'notify': True},
	{'source': 'messages.vala', 'target': 'xsircmessages'},
	{'source': 'ctcp.vala', 'target': 'xsircctcp'},
	{'source': 'achievements.vala', 'target': 'xsircachievements', 'notify': True},
]

for plugin in plugins:
	opt = {
		'features': 'c cshlib',
		'packages': ['xsirc'],
		'vapi_dirs': ['../src', '../vapi'],
		'includes': ['../src', '../vapi'],
		'cflags': ['-include','config.h','-g'],
		'uselib': ['GMODULE', 'GLIB'],
		'use': 'xsirc',
		'linkflags': ['-g'],
		'install_path': bld.env['PREFIX']+'/lib/xsirc'
	}

	if 'notify' in plugin and conf.env['windows'] != 'yes':
		opt['packages'].append('libnotify')
		opt['uselib'].append('NOTIFY')
	
	opt['source'] = plugin['source']
	opt['target'] = plugin['target']

	bld.shlib(**opt)
