#!/usr/bin/env python
# wscript_build
#
# Copyright (c) 2010 Eduardo Niehues
# Distributed under the New BSD License; see LICENSE for details.
bld.shlib(
	source = 'testplugin.vala',
	features = 'c cshlib',
	packages = 'xsirc',
	vapi_dirs = '../src ../vapi',
	includes = '../src',
	target = 'xsirctest',
	uselib = 'GMODULE GLIB',
	use = 'xsirc',
	cflags = ['-g'],
	linkflags = ['-g'],
	install_path = bld.env['PREFIX']+'/lib/xsirc'
)
if conf.env['windows'] == 'yes':
	packs = 'xsirc'
	store = 'GMODULE GLIB'
else:
	packs = 'xsirc libnotify'
	store = 'GMODULE GLIB NOTIFY'
bld.shlib(
	source = 'highlights.vala',
	features = 'c cshlib',
	packages = packs,
	vapi_dirs = '../src ../vapi',
	includes = '../src',
	cflags = ['-include','config.h','-g'],
	target = 'xsirchighlights',
	uselib = store,
	use = 'xsirc',
	linkflags = ['-g'],
	install_path = bld.env['PREFIX']+'/lib/xsirc'
)
bld.shlib(
	source = 'messages.vala',
	features = 'c cshlib',
	packages = 'xsirc',
	vapi_dirs = '../src ../vapi',
	includes = '../src',
	cflags = ['-include','config.h','-g'],
	target = 'xsircmessages',
	uselib = 'GMODULE GLIB',
	use = 'xsirc',
	linkflags = ['-g'],
	install_path = bld.env['PREFIX']+'/lib/xsirc'
)
