#!/bin/bash
cd `dirname "$0"`
cd ..

cat >po/temp-template.pot <<EOF
# XSIRC
# Copyright (C) 2010 Eduardo Niehues
# This file is distributed under the same license as the XSIRC package.
#
# This file was generated by the ./generate.sh script. DO NOT EDIT.
#

msgid ""
msgstr ""
"Project-Id-Version: XSIRC 1.2\n"
"Report-Msgid-Bugs-To: neo.niexs@gmail.com\n"
"POT-Creation-Date: 2011-06-06 01:06+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

EOF

set -ex
xgettext -o po/temp-source.pot --language=C --keyword=_ --keyword=N_ --omit-header -E --add-comments=l10n src/*.vala plugins/*.vala
xgettext -o po/temp-glade.pot --language=Glade --omit-header -E ui/*.ui
msgcat -o po/xsirc.pot --use-first po/temp-template.pot po/temp-source.pot po/temp-glade.pot
rm po/temp-glade.pot po/temp-template.pot po/temp-source.pot
set +x
echo
echo "Successfully generated xsirc.pot."
echo "Use 'msgmerge -U LANG.po xsirc.pot' to merge the new translation template with a translation file, and remember to change all fuzzy matches."
