#!/usr/bin/env python
# wscript_build
#
# Copyright (c) 2010 Eduardo Niehues
# Distributed under the New BSD License; see LICENSE for details.
bld.program(
	source    = ['gui.vala','main.vala','config.vala','server.vala','mircparser.vala','servermanager.vala','irclogger.vala'],
	features  = 'c cprogram',
	packages  = 'gtk+-2.0 gio-2.0 gee-1.0 posix glib-2.0',
	target    = 'xsirc',
	cflags    = ['-include','config.h','-g'],
	linkflags = ['-g'],
	
	uselib    = 'GTK GLIB GIO GEE',
	)
