#!/usr/bin/env python
# wscript_build
#
# Copyright (c) 2010 Eduardo Niehues
# Distributed under the New BSD License; see LICENSE for details.
if bld.env['windows'] == 'yes':
	flags = ['-g','-mingw32','-mwindows']
	source = bld.path.ant_glob('../plugins/*.vala')
else:
	flags = ['-g']
	source = bld.path.ant_glob('*.vala')
bld.stlib(
	source = 'gen_timestamp.c',
	includes = '.. .',
	target = 'timestamp')
if 'windows' in bld.env:
	bld.stlib(
		source = 'gen_timestamp_shlib.c',
		target = 'timestamp_shlib')
to_use = 'timestamp'
bld.program(
	source    = source,
	features  = 'c cprogram',
	packages  = 'gtk+-2.0 gio-2.0 gee-1.0 posix config glib-2.0 gmodule-2.0',
	vapi_dirs = '../vapi',
	includes  = '../vapi',
	target    = 'xsirc',
	use       = to_use,
	cflags    = ['-include','config.h','-g'],
	linkflags = flags,
	uselib    = 'GTK GLIB GIO GEE GMODULE',
	)
if not 'windows' in bld.env:
	bld.shlib(
		source = bld.path.ant_glob('*.vala'),
		features  = 'c cshlib',
		packages  = 'gtk+-2.0 gio-2.0 gee-1.0 posix config glib-2.0 gmodule-2.0',
		vapi_dirs = '../vapi',
		includes  = '../vapi',
		target    = 'xsirc',
		use       = 'timestamp_shlib',
		cflags    = ['-include','config.h','-g'],
		linkflags = flags,
		uselib    = 'GTK GLIB GIO GEE GMODULE',
		)
